@startuml
title Show Stored Locations Scenario
autonumber

actor User
participant TerminalInterface
participant LocationManager
participant DataManager
participant CacheManager

User -> TerminalInterface: showStoredLocatios()
activate TerminalInterface
activate User


opt StoredLocationsData==Empty
TerminalInterface -> LocationManager: fetchStoredLocations()
activate LocationManager
LocationManager -> CacheManager: fetchStoredLocations()
activate CacheManager
CacheManager --> LocationManager: storedLocations
LocationManager --> TerminalInterface: storedLocations
deactivate CacheManager
deactivate LocationManager
end
TerminalInterface -> TerminalInterface: showStoredLocations()
TerminalInterface --> User: "Select Option"

alt showCurrentWeather
    
ref over TerminalInterface,LocationManager,DataManager,CacheManager
    showCurrentWeather
end ref

else showAirReport

ref over TerminalInterface,LocationManager,DataManager,CacheManager
    showAirReport
end ref

else showForecast

ref over TerminalInterface,LocationManager,DataManager,CacheManager
    showForecast
end ref


end
