@startuml

left to right direction
skinparam packageStyle rectangle

actor User as U
actor NotificationSystem as NS
actor CacheUpdation as CU
actor Terminal as T

rectangle "Weather System" {
    usecase "Add location with latitude and longitude" as AddLocationLL
    usecase "Add location with city, country" as AddLocationCC
    usecase "See current weather conditions" as SeeWeather
    usecase "Enable notification" as EnableNotification
    usecase "Raise notification" as RaiseNotification
    usecase "Update cache" as UpdateCache
    usecase "See current air report" as SeeAirPollution
    usecase "See 5 Days Forecast" as Forecast
    usecase "Render Weather Report" as RenderWeatherData
    usecase "Render Air Report" as RenderAirData
    usecase "Render Forecast Report" as RenderForecast
    
    U --> AddLocationLL
    U --> AddLocationCC
    U --> SeeWeather
    U --> EnableNotification
    U --> Forecast
    U --> SeeAirPollution
    CU --> UpdateCache
    NS --> RaiseNotification
    NS --> EnableNotification
    T --> RenderWeatherData
    T --> RenderAirData
    T --> RenderForecast

}

