@startuml
title CurrentWeather Scenario
autonumber
actor User
participant TerminalInterface
participant LocationManager
participant APIService
participant DataManager
participant CacheManager
participant WeatherService

scale 2
User -> TerminalInterface: showForecast()
activate User
TerminalInterface --> User: Enter Location
activate TerminalInterface
User -> TerminalInterface: location

ref over User,TerminalInterface,LocationManager,APIService
    Validate Location
end ref

TerminalInterface -> DataManager: fetchReport(latitude,longitude,"Forecast")
activate DataManager

ref over DataManager,CacheManager,WeatherService
    Fetch Report
end ref
DataManager --> TerminalInterface: forecastReport
deactivate DataManager


ref over TerminalInterface
    RenderForecastReport
end ref



@enduml
